### PR TITLE
Added MaxHeap Program in C++

### PR DESCRIPTION
**Pull request by Obito9596**

### CODE REVIEW

**Comment by Shubham56-droid** [comment]
Hi @Obito9596 pls star this repo and  follow me good work i will merge ur PR thank for contributing

**Comment by Shubham56-droid** [comment]
comment if u have done it

**Comment by Obito9596** [comment]
> comment if u have done it

YUP Done it.

**Comment by Obito9596** [comment]
> Hi @Obito9596 pls star this repo and follow me good work i will merge ur PR thank for contributing

Done

**Pull request merged**
