### PR TITLE
GYM MANAGEMENT SYSTEM

### PR DESCRIPTION
**Pull request by vedanshtandon**
😃😃😃😃This is a mini C++ console Application which flawlessly represents the GYM MANAGEMENT SYSTEM.
This console application is capable of adding new customers and staff members to a gym and store their details and plain
Features of Object oriented programming and File handling has been discussed.

Please Add this mini project beneficial for college and school students 😃😃😃😃

### CODE REVIEW

**Comment by Shubham56-droid** [comment]
pls star this repo and follow me

**Comment by vedanshtandon** [comment]
> pls star this repo and follow me

done sir

**Comment by Shubham56-droid** [comment]
sorry but we don't accept projects

**Comment by vedanshtandon** [comment]
Toh phle batate follow kyu karwae ??????

**Pull request closed without merging**
