### PR TITLE
Added Selection Sort in Java and Python

### PR DESCRIPTION
**Pull request by gohan007**

### CODE REVIEW

**Comment by Shubham56-droid** [comment]
Pls star this repository and follow me and thanks for contribution it will be merged so pls star this repository

**Comment by gohan007** [comment]
Thanks Brother. I have already starred your repository.

**Comment by gohan007** [comment]
Can you resolve the conflicts.?

**Comment by gohan007** [comment]
Brother .. Please merge this branch with main branch. There is no more conflicts.

**Comment by Shubham56-droid** [comment]
thanks bro for contributing

**Pull request merged**
